### ISSUE TITLE
failed to login.

### ISSUE THREAD

**Issue by Plainbroke** [balharrie/MMM-SugarValue#1]
I am suddenly getting failed to login message when MMM-SugarValue runs.  I use the carousel module in slides mode.
It was working fine.  had been for a year or more.   I really like this module, and would like to be able to use it again.
I did remove the module and then reinstalled with git clone, for testing purposes.
But I am still getting the same issue.
Ideas ?
Oh and the Dexcom G6 is still working with my android phones Dexcomg6 app.
Any help is appreciated.

**Comment by balharrie** [comment]
Interesting, I've seen this a few times over the last few weeks, but the plugin always recovers after about 30 mins. Let me have a look and see if there is some logging or improvements that can be made. Out of interest are you connecting to the eu or us server?

**Comment by balharrie** [comment]
Try pulling the latest, it should provide more details on the error. Let me know what message you see.

**Comment by Plainbroke** [comment]
Did the git pull and npm install.  Problem resolved.
Thank you all.
