### ISSUE TITLE
Missing Trend arrow

### ISSUE THREAD

**Issue by Cytron1980** [balharrie/MMM-SugarValue#3]
Hello,

After installation, values ​​and time of the last measurement are displayed but no trend arrows. How can i fix this?

Greetings

**Comment by balharrie** [comment]
@Cytron1980 Have started to see this as well, will investigate.

**Comment by Cytron1980** [comment]
Thought it was my fault. Would it perhaps still be possible to display the difference to the last measurement as a value?
