### ISSUE TITLE
Anyone using this module in Canada

### ISSUE THREAD

**Issue by sami02-source** [balharrie/MMM-SugarValue#9]
Not working for me.
Trying to use the Server: "eu" as I am located in Canada
Have tried "us" server as well.

Using credentials (username and pswd) for the Dexcom Share account (the main device that is connected to the Dexcom transmitter via Bluetooth and is sending data to other phones in our household)

MM runs without any syntax errors...etc, but displays no Dexcom info on the MM screen. Thinking it is a country issue.
Any thoughts welcome. Very new to this.....

**Comment by balharrie** [comment]
I'm currently running it with MagicMirror 2.13.0 (probably not the most recent version to be honest).

My configuration with the username and password "redacted" is:

 {
		module: "MMM-SugarValue",
		position: "top_left",
		config: {
		 server: "eu",
		 username: "<REDACTED>",
		 password: "<REDACTED>",
		units: "mmol",
		lowlimit: 4,
		highlimit: 10
		}
	},

**Comment by balharrie** [comment]
Let me know the versions of MagicMirror and node you are trying to use, and I'll set-up an environment here.

**Comment by sami02-source** [comment]
@balharrie - thank you for the quick response. My script is identical to yours except I have not listed the last 2 variables: lowlimit, highlimit
MM version is 2.28.0 (obtained from package.json file)
Node version is 2.0.18 (obtained from node.js file)

Greatly appreciated!

**Comment by sami02-source** [comment]
update - got the module to work.
Only issue now is on the MM screen where the dexcom number should be, is says "login Fail" and at the top of the MM screen, it states "MMM-Sugar Values needs update. The current installation is 2 value behind on the master branch."

**Comment by balharrie** [comment]
Readme updated
